services:
  db:
    image: bitnami/mariadb:11.8.2-debian-12-r4
    container_name: db
    environment:
    - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/bitnami/mariadb
    restart: always

  wordpress:
    image: bitnami/wordpress:6.8.2-debian-12-r2
    container_name: wordpress
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - WORDPRESS_DATABASE_HOST=${WORDPRESS_DATABASE_HOST}
      - WORDPRESS_DATABASE_PORT_NUMBER=${WORDPRESS_DATABASE_PORT_NUMBER}
      - WORDPRESS_DATABASE_NAME=${WORDPRESS_DATABASE_NAME}
      - WORDPRESS_DATABASE_USER=${WORDPRESS_DATABASE_USER}
      - WORDPRESS_DATABASE_PASSWORD=${WORDPRESS_DATABASE_PASSWORD}
      - WORDPRESS_USERNAME=${WORDPRESS_USERNAME}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
      - WORDPRESS_EMAIL=${WORDPRESS_EMAIL}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
    volumes:
      - wordpress_data:/bitnami/wordpress
    restart: always

volumes:
  mariadb_data:
  wordpress_data: